<?php

namespace Desymfony\DesymfonyBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class PonenteController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Desymfony\DesymfonyBundle\Controller\PonenteController();
        return $instance;
    }
}
